LIBRARY ICE
VERSION LIBRARY_VERSION
EXPORTS
 IceAcceptConnection
 IceAddConnectionWatch
 IceAllocScratch
 IceAppLockConn
 IceAppUnlockConn
 IceAuthFileName
 IceCheckShutdownNegotiation
 IceCloseConnection
 IceComposeNetworkIdList
 IceConnectionNumber
 IceConnectionStatus
 IceConnectionString
 IceFlush
 IceFreeAuthFileEntry
 IceFreeListenObjs
 IceGenerateMagicCookie
 IceGetAuthFileEntry
 IceGetConnectionContext
 IceGetInBufSize
 IceGetListenConnectionNumber
 IceGetListenConnectionString
 IceGetOutBufSize
 IceInitThreads
 IceLastReceivedSequenceNumber
 IceLastSentSequenceNumber
 IceListenForConnections
 IceLockAuthFile
 IceOpenConnection
 IcePing
 IceProcessMessages
 IceProtocolRevision
 IceProtocolSetup
 IceProtocolShutdown
 IceProtocolVersion
 IceReadAuthFileEntry
 IceRegisterForProtocolReply
 IceRegisterForProtocolSetup
 IceRelease
 IceRemoveConnectionWatch
 IceSetErrorHandler
 IceSetHostBasedAuthProc
 IceSetIOErrorHandler
 IceSetPaAuthData
 IceSetShutdownNegotiation
 IceSwapping
 IceUnlockAuthFile
 IceVendor
 IceWriteAuthFileEntry
 _IceTransGetPeerAddr
 _IceTransGetPeerNetworkId
 _IceErrorBadMinor
 _IceErrorBadLength
 _IceErrorBadState
 _IceErrorBadValue
 _IcePaMagicCookie1Proc
 _IcePoMagicCookie1Proc
 _IceRead
 _IceReadSkip
 _IceWrite
 IceListenForWellKnownConnections
 _IceTransGetHostname
 _IceTransSetOption
 _IceTransConnect
 _IceTransClose
 _IceTransOpenCOTSClient
 _IceTransGetConnectionNumber
 _IceTransRead
 _IceTransWrite
 
/* $XFree86: xc/lib/ICE/ICE-def.cpp,v 1.6 2006/01/09 14:58:21 dawes Exp $ */
