#!/bin/sh
# Reassign ownership of the console to root, this should disallow
# assignment of console output to any random users's xterm
# $XFree86: xc/programs/xdm/config/TakeConsole,v 1.2 2006/01/09 15:01:06 dawes Exp $
#
chmod 622 /dev/console
chown root /dev/console
